apiVersion: v1
kind: ConfigMap
metadata:
<#if deployment.configMapName??>    
    name: ${deployment.configMapName}
<#else>    
    name: ${deployment.name}
</#if>
    namespace: ${deployment.namespace}
data:
<#list configmapentries as configmap>
  ${configmap.nameValue}
</#list>
